### ISSUE TITLE
Flexible comment layouts

### ISSUE THREAD

**Issue by tmcphillips** [yesworkflow-org/yw-prototypes#22]
YW-Extract  generally expects comments to occur on a single line of the script and to occupy that entire line. The exception is the `@as alias` comment that must occur on the same line as the `@in`/`@out` comment it qualifies. Users would like to be able to:

* Include multiple YW comments on a single line to minimize the number of lines they occupy.
* Put the `@as` comment on its own line following the line with the comment it qualifies.
* Place YW comments on lines shared with code.

**Comment by ludaesch** [comment]
It'll make parsing a bit harder though, but I think that flexibility is useful.

**Comment by sycao5** [comment]
If a semicolon (;) is used as the indicator of the ending of one YW comments, we can split the multiple YW comments on a single line using the (;).
