### ISSUE TITLE
Publish YesWorkflow to Maven Central

### ISSUE THREAD

**Issue by tmcphillips** [yesworkflow-org/yw-prototypes#24]
YesWorkflow needs to be useable as a Java library as well as a command line tool.  Sharing the YesWorkflow jar by publishing it to Maven Central (http://central.sonatype.org) will make it easy for projects using Maven to depend (directly or indirectly) on specific versions of YesWorkflow and to obtain required artifacts automatically.

Maven Central has created a project space for YesWorkflow (see https://issues.sonatype.org/browse/OSSRH-14297) .  We now need to choose an acceptable open source license, satisfy its requirements, and publish our artifacts.

**Comment by tmcphillips** [comment]
The project pom.xml is now configured to push snapshot versions to Maven Central when the 'deploy' command is used.  The snapshots can be browsed [here](https://oss.sonatype.org/content/repositories/snapshots/org/yesworkflow/yesworkflow/) .

The current snapshot version can be referred to in other Maven projects by adding this dependency:

    <dependency>
        <groupId>org.yesworkflow</groupId>
        <artifactId>yesworkflow</artifactId>
        <version>0.2-SNAPSHOT</version>
    </dependency>

**Comment by csjx** [comment]
This is great Tim. thanks for setting it up.

**Comment by tmcphillips** [comment]
It turns out that to access the YW snapshot version in Maven Central you also must add this repository element as a child of the <repositories> element of a project's pom.xml:

    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>

**Comment by sycao5** [comment]
Hi Tim,

I would like to verify the process of my generating YW snapshot. I do not download this snapshot directly from Maven. I sync’d the YW code from github and recompile using Maven on my local machine. In addition, the depenency libs are at target/dependency. This is the way I find the dependency libs and YW-snapshot lib. 

Please review if there is anything wrong with my approach. Sorry for inconvenice.

Yang

**Comment by tmcphillips** [comment]
What you did should work.  A quick way to check if the jars you've prepared are OK is to compile and run, outside of any project, a simple Java program that uses the YW API.  Try compiling and running it with and without the YW jar and the jars you found in target/dependency on the classpath.
