### ISSUE TITLE
"Getting started with YesWorkflow?"

### ISSUE THREAD

**Issue by olyerickson** [yesworkflow-org/yw-prototypes#28]
Am I correct that anyone wishing to experiment with YW *today* should start at...

https://github.com/yesworkflow-org/yw-prototypes

...and follow the procedure at "Getting started with YesWorkflow?"

The text refers to "two prototypes." Are those prototype workflows, or versions of YW? 

Thanks...

**Comment by tmcphillips** [comment]
The two prototypes mentioned are of the YesWorkflow system itself, one implemented in Java, the other in Python.  At this point the Java implementation has far more functionality and is where development is continuing. We do foresee writing YesWorkflow extensions in Python, however.  

The repository [README](https://github.com/yesworkflow-org/yw-prototypes/blob/master/README.md) focuses on the Java implementation and is definitely the place to start.

**Comment by olyerickson** [comment]
Closing this as we have been successful at getting the .jar working with the Py and R examples. Great!
