### ISSUE TITLE
Simple parser for extracting YW comments from source code

### ISSUE THREAD

**Issue by tmcphillips** [yesworkflow-org/yw-prototypes#5]

**Comment by ludaesch** [comment]
Hi everybody,

Just a short sign of life..

Over the holidays, I was mostly offline but had a bit fun with Python and
hacked some small Python scripts that have similar functionality to the
code that Tim checked in.

Is anybody else contributing code (or planing to)?

Bertram

On Sat, Dec 27, 2014 at 8:25 PM, Timothy McPhillips <
notifications@github.com
