### ISSUE TITLE
Finalize a simple version of comment vocabulary and structure

### ISSUE THREAD

**Issue by swanskysong** [yesworkflow-org/yw-prototypes#8]

**Comment by tmcphillips** [comment]
Note that the Java prototype uses the alias (the token following the `@as` keyword) for matching `@in` with `@out` ports when inferring channels between yw-commented blocks of code.  As @swanskysong points out, this allows the script writer to update a variable within a block (`@in x` and `@out x` on the same block) and then to declare `@in x` on downstream blocks as well, as long as each use of x has a distinct alias.  

Aliases also are used to match `@in` and `@out` comments on the top-level ('workflow') block with `@in` and `@out` comments on blocks ('programs') within the script to model flow of data into and out of the script.

The token following the `@in` or `@out` keyword is used for these purposes if no alias is given.

**Comment by sycao5** [comment]
Hello Team,

Happy new year to everyone and your family!

I have arrived the campus on 30th and spent 2 days to familiar with the local environment. I am reading the code now. Please let me know if there is any task that I can do.

Best regards,

Yang
