### ISSUE TITLE
develop an expected data flow graph of "example.py"

### ISSUE THREAD

**Issue by swanskysong** [yesworkflow-org/yw-prototypes#9]
Serve as a test. The graph is the expected output after running the tool on "example.py"

**Comment by tmcphillips** [comment]
Here is what the Java prototype produces as the graph at the moment:
![example](https://cloud.githubusercontent.com/assets/3218259/5593909/93fc7f1c-91e3-11e4-8370-aebcf1341d36.png)
The command used to produce the graph was:
`yw graph -s src/main/resources/example.py | dot -Tpng > example.png`
where `yw` is a bash alias that refers to the jar built by maven:
`alias yw='java -jar ~/GitRepos/yw-prototypes/target/yesworkflow-0.1-executable.jar'`
